### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by ghost** [JEFF-Media-GbR/Spigot-LightPerms#5]
[16:37:06 ERROR]: Could not pass event PlayerQuitEvent to LightPerms v2.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:499) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1243) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:540) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:236) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1006) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:429) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:793) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:684) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Attachment cannot be null
        at org.bukkit.permissions.PermissibleBase.removeAttachment(PermissibleBase.java:137) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.removeAttachment(CraftHumanEntity.java:136) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        at de.jeff_media.LightPerms.LightPerms.onPlayerQuit(LightPerms.java:132) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Dionysus-"3ccc44b"]
        ... 12 more

**Comment by mfnalex** [comment]
Fixed in 2.1.3
