### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkPizza** [JEFF-Media-GbR/Spigot-LightPerms#6]
`[00:05:25] [Server thread/WARN] [/]: java.net.ConnectException: Connection timed out
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.nio.ch.Net.connect0(Native Method)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.nio.ch.Net.connect(Net.java:579)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.nio.ch.Net.connect(Net.java:568)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
[00:05:25] [Server thread/WARN] [/]:    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[00:05:25] [Server thread/WARN] [/]:    at java.base/java.net.Socket.connect(Socket.java:633)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[00:05:25] [Server thread/WARN] [/]:    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[00:05:25] [Server thread/WARN] [/]:    at de.jeff_media.updatechecker.UpdateChecker.lambda$checkNow$5(UpdateChecker.java:203)
[00:05:25] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.2.9/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:102)
[00:05:25] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.2.9/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:05:25] [Server thread/WARN] [/]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:05:25] [Server thread/WARN] [/]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:05:25] [Server thread/WARN] [/]:    at java.base/java.lang.Thread.run(Thread.java:833)
[00:05:25] [Server thread/WARN] [de.je.Li.LightPerms/]: [LightPerms] Could not check for updates.`

**Comment by mfnalex** [comment]
Looks like your firewall is blocking outgoing requests. Just disable the update checker in config.yml
